### ISSUE TITLE
Error on collect_swap

### ISSUE THREAD

**Issue by starpause** [versumstudios/report-bugs#102]
```
{
  "props": {
    "amount": 1,
    "swap_id": 43870
  },
  "send": {
    "amount": 1000000,
    "mutez": true,
    "storageLimit": 250,
    "gasLimit": 200000
  },
  "error": {
    "errorDetail": {
      "message": "Network Error",
      "name": "Error",
      "stack": "Error: Network Error\n    at e.exports (https://versum.xyz/_next/static/chunks/pages/_app-dc02d1c5841c90b0.js:1:198435)\n    at XMLHttpRequest.b.onerror (https://versum.xyz/_next/static/chunks/pages/_app-dc02d1c5841c90b0.js:1:193413)\n    at XMLHttpRequest.a (https://versum.xyz/_next/static/chunks/pages/_app-dc02d1c5841c90b0.js:1:65048)",
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 30000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*"
        },
        "url": "https://eu01-node.teztools.net/chains/main/blocks/head",
        "method": "get",
        "responseType": "json"
      },
      "status": null
    },
    "name": "HttpRequestFailed"
  },
  "message": "Error on collect_swap"
}
```

**Comment by starpause** [comment]
I was trying to purchase https://versum.xyz/token/versum/22655

Versum Market has my funds but I haven't gotten the NFT - [explorer tx](https://tzkt.io/ooahduFyVDp8XphxRUAKyEiAdyqC99hMQdLvewnPdb2kZSxW582)

**Comment by andrevenancio** [comment]
Hi @starpause thanks for reporting this issue. Some times the nodes we use to communicate between versum / wallets / blockchain get busy. We decided to report **any** error we catch instead of just adding a generic error message. So this particular error ** HttpRequestFailed** means that the node wasn't able to complete the transaction. 

This sometimes can happen, and its not related to versum but the nodes, how many people are using them or even your internet connection.

My rule of thumb for this situations is:
1) try again. If it fails then
2) change RPC node. Head over to settings / general https://versum.xyz/settings/general and change your rpc node to another node and then try to complete the transaction again.

**Comment by andrevenancio** [comment]
Also, you actually have a copy of the token. its on the token history and you are a collector. closing.
