### ISSUE TITLE
On-chain verification not working

### ISSUE THREAD

**Issue by brnmerli** [versumstudios/report-bugs#2]
I'm trying to get the "on-chain verification", but it's not working when it calls for the wallet. It gives me the "Parameters Invalid" error on the platform and "Simulation error: A FAILWITH instruction was reached {"prim":"Unit"}" on the wallet.

Already tried every node in Versum, with and without VPN. Already tried to clear cache, resync wallet, etc.

OS: Windows 10
Browser: Opera GX
Wallet: Kukai
Adress: tz1gmrBAebCWi253y8ivoEZrGAiBmDTv6mn6

**Comment by toiminto** [comment]
Same issue, using temple wallet & chrome, windows 10
```
[
  {
    "kind": "temporary",
    "id": "proto.011-PtHangz2.michelson_v1.runtime_error",
    "contract_handle": "KT1NUrzs7tiT4VbNPqeTxgAFa4SXeV1f3xe9"
  },
  {
    "kind": "temporary",
    "id": "proto.011-PtHangz2.michelson_v1.script_rejected",
    "location": 223,
    "with": {
      "prim": "Unit"
    }
  }
]
```

**Comment by ixt** [comment]
For those of you who find yourself here before the fix is implemented, I was having issues for a while with getting on chain verification, and eventually it just worked. I was using kukai at the time, but others who are successful have used temple too. If you have the time to waste you can retry and eventually get success (refreshing the settings page between each attempt).

**Comment by andrevenancio** [comment]
There were several updates today. Does it solve this for you?
