### ISSUE TITLE
changing username and URL

### ISSUE THREAD

**Issue by memoakten** [versumstudios/report-bugs#28]
I was automatically assigned a username and URL (https://versum.xyz/user/memo) and I would love to be able to change this (to make it the same as I have on all other platforms).

**Comment by LeithBA** [comment]
Hi! https://versum.xyz/user/memotv also works. Is this what you need?

**Comment by memoakten** [comment]
actually I was after https://versum.xyz/user/memoakten but it seems that also works!

**Comment by skenaja** [comment]
All your registered names via external ID providers are reserved for you to prevent name squatters. The UI to allow you to choose your preferred URL is coming soon.

**Comment by memoakten** [comment]
that's a great idea! thanks for the clarification.

**Comment by postspectacular** [comment]
Somewhat related: I'm too waiting on the above UI improvement to select preferred user ID. But also reading above that you're reserving all registered names from external ID providers, how will you be dealing with scammers self-attesting someone else's username and then seemingly getting priority, as in this (my) case:

Scammer (squatting my user name): https://versum.xyz/user/toxi

Scammer's tzProfile (self attestation only): https://tzprofiles.com/view/tz1f9cshgR7BZuddZrN2YgpWdhjtd6UbmGWW

(Verified scammer, since the account has been copyminting my pieces here: https://www.fxhash.xyz/u/flash) 

My fully verified tzProfile: https://tzprofiles.com/view/tz1d4ThofujwwaWvxDQHF7VyJfaeR2ay3jhf

Will there be a mechanism to de-prioritize self-attested tzprofiles when it comes to naming conflicts?
