### ISSUE TITLE
Not receiving secondary sale tezos

### ISSUE THREAD

**Issue by inputhumanname** [versumstudios/report-bugs#5]
**Describe the bug**

i sold a piece by Gingey, but have not received the tezos. My profile is verified with tz profiles but fails to do on chain verification on versum. 

My address, tz1apoQC5dPRwQTy1XTLipwakvUupzSUHmym
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frycomputer** [comment]
You need to have on chain verification before you are able to receive tez from secondary sales, otherwise the tez is locked in an escrow contract that will pay out after 2 weeks. I understand this to be a bot/malicious activity prevention measure. There are issues with verification that are being worked on already, and there will also soon be a button to claim back this tezos within the settings UI. If you get verified before then, you can also use BCD to withdraw funds:

From Discord:
Once verified, use the following contract call to claim your tez. enter your wallet address in source and '0' in amount: [https://better-call.dev/mainnet/KT1NUrzs7tiT4VbNPqeTxgAFa4SXeV1f3xe9/interact?entrypoint=withdraw_outstanding_tez](https://better-call.dev/mainnet/KT1NUrzs7tiT4VbNPqeTxgAFa4SXeV1f3xe9/interact?entrypoint=withdraw_outstanding_tez)
