### ISSUE TITLE
price info not showed

### ISSUE THREAD

**Issue by raspcwalter** [versumstudios/report-bugs#92]
**Describe the bug**
the object is showed without price information 

**To Reproduce**

1. Go to https://versum.xyz/token/versum/16201
2. Scroll down to the bottom
4. Price information is not showed / there is no way to collect it 

**Expected behavior**
Price info should be available / I should be able to collect it 

**Screenshots**

**Desktop (please complete the following information):**

- OS: iOS (MacBook Air)
- Browser chrome 
- Version Versão 99.0.4844.51 (Versão oficial) (x86_64)

**Additional context**
it works at my smart phone (Samsung 9)

<img width="1440" alt="Captura de Tela 2022-03-06 às 23 51 16" src="https://user-images.githubusercontent.com/97717384/156960001-f2d44f9f-2512-49d2-bc9c-1abe1ea74a0a.png">

**Comment by andrevenancio** [comment]
The screenshot u send is this the most "down" you can scroll? Because the objective of this screen is to see the art without any distractions. As you scroll down you will see the price (which you set to zero tezos 3 days ago) and you will see other relevant information.![image](https://user-images.githubusercontent.com/1734502/157006175-e46fdd83-8878-4a71-b188-2a4e68a678fd.png)

**Comment by raspcwalter** [comment]
Hi André,

What happens is that the first time I enter the object, that is the screen.
If I get the URL and press enter at location bar, then I can scroll down to
more details and collect it pressing the button with price.

Thank you, Igor

**Comment by andrevenancio** [comment]
Hi @raspcwalter which browser do you have? I can't replicate that. If I access the url directly I can scroll
